import type { ShotSound } from "./AudioManager";

export interface WeaponDef {
  id: string;
  name: string;
  icon: string;
  description: string;
  baseCooldown: number;
  baseBulletCount: number;
  baseBulletSpread: number;
  baseBulletSpeed: number;
  damageMultiplier: number;
  basePierce: number;
  bulletRadius: number;
  bulletColor: number;
  lifetime: number;
  homing: boolean;
  shotSound: ShotSound;
  isEvolution?: boolean;
}

export const ALL_WEAPONS: WeaponDef[] = [
  {
    id: "standard",
    name: "Standard",
    icon: "---",
    description: "Balanced all-rounder",
    baseCooldown: 150,
    baseBulletCount: 1,
    baseBulletSpread: 0.15,
    baseBulletSpeed: 600,
    damageMultiplier: 1,
    basePierce: 0,
    bulletRadius: 3,
    bulletColor: 0xffff00,
    lifetime: 0,
    homing: false,
    shotSound: "soft",
  },
  {
    id: "shotgun",
    name: "Shotgun",
    icon: "|||",
    description: "Wide burst, deadly up close, short range",
    baseCooldown: 400,
    baseBulletCount: 5,
    baseBulletSpread: 0.5,
    baseBulletSpeed: 500,
    damageMultiplier: 1,
    basePierce: 0,
    bulletRadius: 2.5,
    bulletColor: 0xff8833,
    lifetime: 800,
    homing: false,
    shotSound: "kick",
  },
  {
    id: "laser",
    name: "Laser",
    icon: "===",
    description: "Rapid needles that pierce through enemies",
    baseCooldown: 80,
    baseBulletCount: 1,
    baseBulletSpread: 0,
    baseBulletSpeed: 1200,
    damageMultiplier: 0.5,
    basePierce: 2,
    bulletRadius: 1.5,
    bulletColor: 0x00ffff,
    lifetime: 0,
    homing: false,
    shotSound: "pulse",
  },
  {
    id: "cannon",
    name: "Cannon",
    icon: "(O)",
    description: "Slow heavy slugs that devastate on hit",
    baseCooldown: 600,
    baseBulletCount: 1,
    baseBulletSpread: 0,
    baseBulletSpeed: 350,
    damageMultiplier: 3,
    basePierce: 0,
    bulletRadius: 6,
    bulletColor: 0xff4400,
    lifetime: 0,
    homing: false,
    shotSound: "808",
  },
  {
    id: "homing",
    name: "Homing",
    icon: "@>@",
    description: "Bullets seek enemies, never miss",
    baseCooldown: 200,
    baseBulletCount: 1,
    baseBulletSpread: 0,
    baseBulletSpeed: 400,
    damageMultiplier: 0.7,
    basePierce: 0,
    bulletRadius: 2.5,
    bulletColor: 0x44ff44,
    lifetime: 0,
    homing: true,
    shotSound: "bubble",
  },

  // --- Evolutions ---
  {
    id: "nova",
    name: "Nova",
    icon: "***",
    description: "360° burst of destruction",
    baseCooldown: 500,
    baseBulletCount: 8,
    baseBulletSpread: Math.PI * 2,
    baseBulletSpeed: 500,
    damageMultiplier: 1.2,
    basePierce: 0,
    bulletRadius: 3,
    bulletColor: 0xff6600,
    lifetime: 600,
    homing: false,
    shotSound: "kick",
    isEvolution: true,
  },
  {
    id: "railgun",
    name: "Railgun",
    icon: ">>|",
    description: "Hypersonic beam pierces everything",
    baseCooldown: 120,
    baseBulletCount: 1,
    baseBulletSpread: 0,
    baseBulletSpeed: 2000,
    damageMultiplier: 0.8,
    basePierce: 10,
    bulletRadius: 1.5,
    bulletColor: 0x00ffff,
    lifetime: 0,
    homing: false,
    shotSound: "pulse",
    isEvolution: true,
  },
  {
    id: "nuke",
    name: "Nuke",
    icon: "(X)",
    description: "Massive slug of annihilation",
    baseCooldown: 1200,
    baseBulletCount: 1,
    baseBulletSpread: 0,
    baseBulletSpeed: 200,
    damageMultiplier: 8,
    basePierce: 3,
    bulletRadius: 12,
    bulletColor: 0xff2200,
    lifetime: 2000,
    homing: false,
    shotSound: "808",
    isEvolution: true,
  },
  {
    id: "swarm",
    name: "Swarm",
    icon: ">>@",
    description: "Homing missile barrage",
    baseCooldown: 250,
    baseBulletCount: 4,
    baseBulletSpread: 0.8,
    baseBulletSpeed: 420,
    damageMultiplier: 0.6,
    basePierce: 0,
    bulletRadius: 2.5,
    bulletColor: 0x88ff44,
    lifetime: 0,
    homing: true,
    shotSound: "bubble",
    isEvolution: true,
  },
  {
    id: "minigun",
    name: "Minigun",
    icon: "|||",
    description: "Relentless bullet stream",
    baseCooldown: 40,
    baseBulletCount: 1,
    baseBulletSpread: 0.2,
    baseBulletSpeed: 700,
    damageMultiplier: 0.4,
    basePierce: 0,
    bulletRadius: 2,
    bulletColor: 0xffff88,
    lifetime: 0,
    homing: false,
    shotSound: "soft",
    isEvolution: true,
  },
];

export function getWeapon(id: string): WeaponDef {
  return ALL_WEAPONS.find((w) => w.id === id) ?? ALL_WEAPONS[0];
}
